services:
  - type: web
    name: eventifyx-backend
    env: node
    plan: free
    rootDir: backend
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
    buildCommand: npm install
    startCommand: node utils/server.js
